# Generated by Django 5.0.6 on 2024-12-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicUser",
            fields=[
                ("basic_user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("pwd_hash", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                ("platform_id", models.AutoField(primary_key=True, serialize=False)),
                ("platform_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=200)),
                ("deal", models.CharField(max_length=200)),
                ("shop_name", models.CharField(max_length=200, unique=True)),
                ("location", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("img", models.URLField(max_length=1000)),
                ("web", models.URLField(max_length=1000)),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.platform"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "price_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("update_date", models.DateField()),
                ("update_time", models.TimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubProduct",
            fields=[
                ("sub_product_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.basicuser"
                    ),
                ),
            ],
        ),
    ]
