# Generated by Django 5.0.6 on 2024-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_product_img_alter_product_web"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shop_name",
            field=models.CharField(max_length=200),
        ),
    ]
