# Generated by Django 5.0.6 on 2024-12-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_emailcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicuser",
            name="jingdong_account",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="basicuser",
            name="jingdong_password",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="basicuser",
            name="taobao_account",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="basicuser",
            name="taobao_password",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
