# Generated by Django 5.0.6 on 2024-12-25 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_basicuser_jingdong_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cookies",
            fields=[
                ("cookies_id", models.AutoField(primary_key=True, serialize=False)),
                ("cookie", models.TextField()),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.platform"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.basicuser"
                    ),
                ),
            ],
        ),
    ]
