# Generated by Django 5.0.6 on 2024-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_cookies"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookies",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
