# Generated by Django 5.0.6 on 2024-12-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_cookies_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basicuser",
            old_name="taobao_account",
            new_name="weipinhui_account",
        ),
        migrations.RenameField(
            model_name="basicuser",
            old_name="taobao_password",
            new_name="weipinhui_password",
        ),
    ]
